# Apsara Assistant — backend developer workflow
# Run `make help` to list targets.

.DEFAULT_GOAL := help
.PHONY: help install env secret run migrate revision downgrade \
        up down logs psql build test lint

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

install: ## Install Python dependencies into the active venv
	pip install -r requirements.txt

env: ## Create .env from the local template (won't overwrite)
	@test -f .env && echo ".env already exists" || (cp deploy/.env.local .env && echo "Created .env from deploy/.env.local")

secret: ## Generate a strong SECRET_KEY
	@openssl rand -hex 32

# ── Local (bare metal, uses your local Postgres / DATABASE_URL) ───────────────
run: ## Run the API with autoreload (http://localhost:8000)
	uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

migrate: ## Apply all DB migrations
	alembic upgrade head

revision: ## Create a new autogenerated migration:  make revision m="add x"
	alembic revision --autogenerate -m "$(m)"

downgrade: ## Roll back the last migration
	alembic downgrade -1

# ── Docker (local stack: Postgres + API) ─────────────────────────────────────
up: ## Start the local Docker stack (Postgres + API)
	docker compose up --build

down: ## Stop the local Docker stack
	docker compose down

logs: ## Tail API logs from the Docker stack
	docker compose logs -f api

psql: ## Open a psql shell on the Docker Postgres
	docker compose exec db psql -U apsara -d apsara

build: ## Build the production image
	docker build -t apsara-api:latest .

# ── Quality (placeholders — wire up when tests/linter are added) ─────────────
test: ## Run the test suite
	pytest

lint: ## Lint the codebase
	ruff check app
