# Apsara Assistant — backend developer workflow
# Run `make help` to list targets.

.DEFAULT_GOAL := help
.PHONY: help install install-dev env secret run migrate revision downgrade \
        up down logs psql build test lint

# Use the repo's venv when it exists so targets work without activating it
# first; otherwise fall back to whatever python is on PATH.
VENV := venv
PY := $(shell test -x $(VENV)/bin/python && echo $(VENV)/bin/python || echo python3)

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

install: ## Install runtime dependencies
	$(PY) -m pip install -r requirements.txt

install-dev: ## Install runtime + test/lint dependencies
	$(PY) -m pip install -r requirements-dev.txt

env: ## Create .env from the local template (won't overwrite)
	@test -f .env && echo ".env already exists" || (cp deploy/.env.local .env && echo "Created .env from deploy/.env.local")

secret: ## Generate a strong SECRET_KEY
	@openssl rand -hex 32

# ── Local (bare metal, uses your local Postgres / DATABASE_URL) ───────────────
run: ## Run the API with autoreload (http://localhost:8000)
	$(PY) -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

migrate: ## Apply all DB migrations
	$(PY) -m alembic upgrade head

revision: ## Create a new autogenerated migration:  make revision m="add x"
	$(PY) -m alembic revision --autogenerate -m "$(m)"

downgrade: ## Roll back the last migration
	$(PY) -m alembic downgrade -1

# ── Docker (local stack: Postgres + API) ─────────────────────────────────────
up: ## Start the local Docker stack (Postgres + API)
	docker compose up --build

down: ## Stop the local Docker stack
	docker compose down

logs: ## Tail API logs from the Docker stack
	docker compose logs -f api

psql: ## Open a psql shell on the Docker Postgres
	docker compose exec db psql -U apsara -d apsara

build: ## Build the production image
	docker build -t apsara-api:latest .

# ── Quality ──────────────────────────────────────────────────────────────────
test: ## Run the test suite
	$(PY) -m pytest

lint: ## Lint the codebase
	$(PY) -m ruff check app tests
