from __future__ import annotations

from pydantic import BaseModel, Field


class WebsiteChatRequest(BaseModel):
    # Stable per-visitor id generated by the widget (e.g. stored in localStorage)
    session_id: str = Field(min_length=1, max_length=128)
    message: str = Field(min_length=1)
    # Optional visitor-provided display name
    name: str | None = None


class WebsiteChatResponse(BaseModel):
    reply: str
