"""add platform connections and message external id

Revision ID: 39f82216cc10
Revises: a973405bc97a
Create Date: 2026-08-10 00:13:52.570380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39f82216cc10'
down_revision: Union[str, None] = 'a973405bc97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('auto_reply', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_platform_external_id')
    )
    op.create_index(op.f('ix_platform_connections_external_id'), 'platform_connections', ['external_id'], unique=False)
    op.create_index(op.f('ix_platform_connections_user_id'), 'platform_connections', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_column('messages', 'external_id')
    op.drop_index(op.f('ix_platform_connections_user_id'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_external_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    # ### end Alembic commands ###
