"""add verification codes and hot-path indexes

Revision ID: 59abb3659bae
Revises: d98a957b8869
Create Date: 2026-08-09 14:50:25.104135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59abb3659bae'
down_revision: Union[str, None] = 'd98a957b8869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_code_hash'), 'verification_codes', ['code_hash'], unique=False)
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Postgres does not index foreign keys automatically, and every one of these
    # columns is the filter on a query the app runs constantly: the seller scope
    # on each list endpoint, and the conversation lookup the chat endpoint makes
    # on every message. Without them each call sequentially scans the table.
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'])
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'])
    op.create_index('ix_conversations_customer_id', 'conversations', ['customer_id'])
    op.create_index('ix_customers_user_id', 'customers', ['user_id'])
    op.create_index('ix_products_user_id', 'products', ['user_id'])
    op.create_index('ix_orders_user_id', 'orders', ['user_id'])
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'])
    op.create_index('ix_attachments_message_id', 'attachments', ['message_id'])


def downgrade() -> None:
    op.drop_index('ix_attachments_message_id', table_name='attachments')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_index('ix_products_user_id', table_name='products')
    op.drop_index('ix_customers_user_id', table_name='customers')
    op.drop_index('ix_conversations_customer_id', table_name='conversations')
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_index('ix_messages_conversation_id', table_name='messages')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_code_hash'), table_name='verification_codes')
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
