"""add shop currency and order currency snapshot

Revision ID: a973405bc97a
Revises: 59abb3659bae
Create Date: 2026-08-09 23:41:06.542650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a973405bc97a'
down_revision: Union[str, None] = '59abb3659bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    op.add_column('users', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.drop_column('orders', 'currency')
    # ### end Alembic commands ###
