"""add order payment fields

Revision ID: df4b77207c2e
Revises: c0a367fcf249
Create Date: 2026-08-10 19:48:33.041013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df4b77207c2e'
down_revision: Union[str, None] = 'c0a367fcf249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.String(), server_default='unpaid', nullable=False))
    op.add_column('orders', sa.Column('stripe_session_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_stripe_session_id'), 'orders', ['stripe_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_stripe_session_id'), table_name='orders')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'stripe_session_id')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
